### PR TITLE
docs: update library descriptions

### PR DESCRIPTION
**Pull request by mattrosno**
Closes https://github.com/carbon-design-system/carbon-platform/issues/1027
See https://github.com/carbon-design-system/carbon-platform/issues/1109

This PR update library descriptions for IBM Products and IBM Security that you see here:

https://next.carbondesignsystem.com/libraries

and in the library detail pages:

https://next.carbondesignsystem.com/libraries/ibm-cloud-cognitive
https://next.carbondesignsystem.com/libraries/ibm-security

This PR also fixes backgrounds in 10 thumbnails that you see when hovering catalog items, and adds a missing thumbnail as well.

#### What did you change?

- Library descriptions
- Asset thumbnails

#### How did you test and verify your work?

- I ran the Carbon platform web-app locally, fetching the data from this branch, to verify changes.

### CODE REVIEW

**Comment by mattrosno** [comment]
New descriptions:
image

**Comment by mattrosno** [comment]
Confirmation that this fixes the missing thumbnail identified here: https://github.com/carbon-design-system/carbon-platform/pull/1127#issuecomment-1211433470
image

**Review by alisonjoseph — APPROVED** [review]

**Review by elycheea — APPROVED** [review]
👍

**Review by francinelucca — APPROVED** [review]
LGTM!
image

**Comment by mattrosno** [comment]
@cameroncalder can you review the updated IBM Security library description here? https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2197#issuecomment-1219894824

You can see all of the new library descriptions here: https://airtable.com/shrdwElZNyJdGtZkS/tblE2Y75BfY0Z0T2O

**Comment by elycheea** [comment]
Confirmed that Security description was reviewed by @amtoussam and @jlongshore initially.

**Pull request merged**
