### PR TITLE
chore(Datagrid): fix sticky action columns and empty toolbar issue

### PR DESCRIPTION
**Pull request by matthewgallo**
Contributes to https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1977

Fixes the issue of the sticky actions column not sticking anymore. In addition, there was one small issue I noticed after the batch actions work. We were accidentally rendering an empty toolbar which was taking up empty white space at the top of the datagrid. This change removes that if no toolbar is passed.

#### What did you change?
```
packages/cloud-cognitive/src/components/Datagrid/Datagrid.stories.js
packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js
packages/cloud-cognitive/src/components/Datagrid/styles/_datagrid.scss
```
#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by davidmenendez — APPROVED** [review]

**Comment by elycheea** [comment]
@allcontributors add @davidmenendez for review

**Comment by elycheea** [comment]
@Ratheeshrajan Can you review once you’re back on Monday? I think this is related to some changes you’ve worked on.

**Comment by Ratheeshrajan** [comment]
@matthewgallo While reviewing the sticky action change, I found a few issues.
1. The scrollbar styles have been changed to be thicker.
Screenshot 2022-08-22 at 2 46 28 PM
2. Standard 'table' behaviors will not work while 'display: flex' is set. For example, 'colspan' for 'td'. This will cause layout issues in the empty state.
Screenshot 2022-08-22 at 2 51 47 PM

I'm hoping that removing 'overflow: hidden' from the '.c4p—datagrid grid-container table' will resolve the sticky column issue.
Screenshot 2022-08-22 at 2 42 30 PM

**Review by Ratheeshrajan — APPROVED** [review]
Changes look good to me.

**Comment by elycheea** [comment]
@allcontributors add @Ratheeshrajan for code and review

**Pull request merged**
