### PR TITLE
fix(HTTP errors): responsive behaviour

### PR DESCRIPTION
**Pull request by Ratheeshrajan**
Contributes to #1796 
HTTP Errors pattern responsive behavior. Broken in smaller media breakpoints

#### What did you change?

Fixed responsive behavior in `md` and `sm` media breakpoints to match with the [design spec](https://www.figma.com/file/Yz74b1hPqqYWwEtmcPqojq/branch/0o1SzPAXFCVSlCPiOiWYEa/Carbon-for-IBM-Products-Design-Kit?node-id=2097%3A5359).

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Comment by lee-chase** [comment]
@Ratheeshrajan to update the snapshots run the tests with `-u` e.g. `yarn test:c4p -u`

**Review by lee-chase — DISMISSED** [review]
Snapshots need updating as per previous comment.

**Review by matthewgallo — CHANGES_REQUESTED** [review]
While on the smaller breakpoint, this does seem better. On larger breakpoints, the placement of the svg seems a bit off now, it is a lot further away from the content than it was previously. Maybe it's worth checking with the designer to get some more details.

**Comment by Ratheeshrajan** [comment]
@matthewgallo snapshot updated.

**Review by matthewgallo — APPROVED** [review]

**Pull request merged**
