### PR TITLE
feat: add dense, short, and stacked options to DescriptionList Module

### PR DESCRIPTION
**Pull request by skamath2000**
Contributes to #1500 

The PR adds support for dense spacing, short spacing, and a responsive stacked layout for the DescriptionListModule in Carbon for IBM Security when specified by the developer. The module can have a default layout (side-by-side), a stacked layout, or toggle between the two when a screen is smaller than 320px.

#### What did you change?
Added additional props to the DescriptionListModule so developers can specify if dense spacing should be used, if short spacing should be used, and which layout mode should be used.
Added styling support for the props.
Created a dense and stacked variant demonstrating the dense spacing and stacked layout.
Created a short variant demonstrating the short spacing.

#### How did you test and verify your work?
`yarn test` was run. Verified the changes on the development server.

#### Design specs
Specs provided by Cameron Calder.
Screen Shot 2021-12-17 at 12 13 07 PM

Looking for any feedback on technical approach.

### CODE REVIEW

**Comment by lee-chase** [comment]
Currently failing tests @skamath2000. Can you recitify?

**Comment by skamath2000** [comment]
Updated security snapshots. This should fix the failing tests. Waiting for status of the tests to be reported.

**Review by lee-chase — APPROVED** [review]

**Comment by elycheea** [comment]
@SimonFinney @dbrugger Can one of you provide a review?

**Comment by dcwarwick** [comment]
@skamath2000 sorry, it looks like the security snapshot needs regenerating again :-) then we can re-approve.

@SimonFinney how should we handle security package updates going forward? Are we ok at this point to review, approve and merge updates that people contribute? I know there was some shadowing/parallel thing happening at one stage -- is that still the case, or was that just temporary while transitioning the code into this repo?

**Comment by SimonFinney** [comment]
> Are we ok at this point to review, approve and merge updates that people contribute?

Thanks for raising — I believe it's safe to proceed as there's no activity in the original repo.

As a side note, this package is at end-of-life and should see little contribution outside of the scheduled dependency upgrades and critical bug fixes from Security application teams. The purpose of transitioning the code into the monorepo is to support teams migrating from `@carbon/ibm-security` to `ibm-products`.

**Comment by davidmenendez** [comment]
@SimonFinney what's the status here?

**Review by amtoussam — DISMISSED** [review]

**Comment by matthewgallo** [comment]
To avoid the yarn issues, @amtoussam has opened https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2095 which adds these same changes

**Pull request closed without merging**
