### PR TITLE
feat: add options-tile component

### PR DESCRIPTION
**Pull request by janhassel**
Adds the implementation of the [OptionsTile component](https://pages.github.ibm.com/cdai-design/pal/components/options-tile/usage)

#### What did you change?
- Added `<OptionsTile />` component, styles, stories and tests

#### How did you test and verify your work?
- Manual testing with storybook
- Automated testing

### CODE REVIEW

**Review by lee-chase — CHANGES_REQUESTED** [review]
Can we make the toggle toggle as well as report an action?

**Comment by janhassel** [comment]
@lee-chase Just as a demo in the storybook or would you suggest to have the component control its state?

**Comment by lee-chase** [comment]
> @lee-chase Just as a demo in the storybook or would you suggest to have the component control its state?

Have the story react to the change of state. Something like

```
const TemplateStatic = ({enabled, ...rest}) => {
  const [liveEnabled, setaLiveEnabled] = useState(enabled);
  const toggleAction = action('onToggle');
  const handleToggle = (ev) => {
    toggleActionS(ev);
    setLiveEnabled(ev.target.value);
  };
  return <OptionsTile onToggle={handleToggle} {...rest} enabled={liveEnabled}/>;
};
```

**Comment by janhassel** [comment]
@lee-chase 👍  just pushed the update

**Comment by lee-chase** [comment]
> @lee-chase 👍 just pushed the update

@janhassel  the story action call returns a function to be called by the event handler. This is why currently no output is logged.

**Review by lee-chase — APPROVED** [review]

**Pull request merged**
