### PR TITLE
feat(cloud-cognitive): log jest coverage to terminal

### PR DESCRIPTION
**Pull request by markkulube**
Contributes to #1781 

Update the jest configuration in the `cloud-cognitive` scope to log coverage summary to terminal.

#### What did you change?
updated the `coverageReporters` array in the jest config with `text` and` text-summary` options.
https://github.com/markkulube/ibm-cloud-cognitive/blob/mkulube-coverage-summary/packages/cloud-cognitive/jest.config.js#L8-L9

#### How did you test and verify your work?

`yarn test --coverage src/components/Datagrid/Datagrid.test.js`

image

image

image

### CODE REVIEW

**Review by matthewgallo — DISMISSED** [review]

**Comment by markkulube** [comment]
@matthewgallo 

Re-requesting as I added safe checks!

From

`jestConfig.coverageReporters.push('text', 'text-summary');`

to 

`jestConfig?.coverageReporters?.push('text', 'text-summary');`

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Hey @markkulube, I was thinking about this a little bit more. Updating the config in this manner will override the settings from `config/jest-config-ibm-cloud-cognitive/index.js`. I think what may be best is to add `text, text-summary` to the `coverageReporters` array in that file.

**Review by matthewgallo — COMMENTED** [review]
Sorry nevermind, this does add to the `coverageReporters` array but I think it should still be set from `config/jest-config-ibm-cloud-cognitive/index.js` so that all of the configuration is together in one place.

**Comment by markkulube** [comment]
> Sorry nevermind, this does add to the `coverageReporters` array but I think it should still be set from `config/jest-config-ibm-cloud-cognitive/index.js` so that all of the configuration is together in one place.

@matthewgallo 

Got it!

The `text` and `text-summary` options have been declared in [config/jest-config-ibm-cloud-cognitive/index.js#L27-L28](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2003/files#diff-66e0ea7835c54f690aeb2385884b358aa2f66be417d4ecd659361e7a90f00f72R27-R28)

**Pull request merged**
