### PR TITLE
PR for #64: add side panel subtitle micro interaction

### PR DESCRIPTION
**Pull request by matthewgallo**
Contributes to #64 

In the design for the side panel component, there is a micro interaction in which the subtitle animates up out of the view when scrolling occurs (see attached gif). This PR adds that interaction.
side-panel-scroll-header

#### What did you change?
`SidePanel.js`
`SidePanel.stories.js`
`_side-panel.scss`

#### How did you test and verify your work?
Verified in storybook

### CODE REVIEW

**Comment by lee-chase** [comment]
In the design, the subtitle fades and moves with scroll. 

In the implementation, the subtitle jumps off the screen at the same time as the title morphs from its larger size to smaller. This detracts for the title transformation making the whole thing feel a bit rushed.

Should the subtitle just fade and disappear under the title with scroll?

**Review by lee-chase — CHANGES_REQUESTED** [review]
See comment, probably one for the designer but the interaction is different to that of the title and we are aiming for consistency.

**Review by davidmenendez — DISMISSED** [review]

**Comment by matthewgallo** [comment]
Closing in favor of #585

**Comment by matthewgallo** [comment]
The title animation issue will be addressed in a future PR

**Pull request closed without merging**
