### PR TITLE
build(cli): generate current year

### PR DESCRIPTION
**Pull request by SimonFinney**
**New**

Generate current year for templates

### CODE REVIEW

**Review by lee-chase — COMMENTED** [review]
Why is the same year written out twice?

**Comment by SimonFinney** [comment]
@lee-chase Good question - it's [blindly followed from Carbon](https://github.com/carbon-design-system/carbon/search?q=Copyright+IBM+Corp.+2021) so maybe @joshblack has additional context around the format of the copyright notice?

**Comment by joshblack** [comment]
@lee-chase @SimonFinney basically the way the copyright banner work is that the first year is the "initial release year", the second year is the "last major update year", at least how I understand it. 

We're in the process now of trying to find a good eslint/stylelint rule to help out with making these `2016, 2020` 👍

**Comment by lee-chase** [comment]
Well, in that case, I approve. ;-)

**Review by lee-chase — APPROVED** [review]

**Pull request merged**
