### PR TITLE
build: Action to cherry pick changes from `main` to `v2`

### PR DESCRIPTION
**Pull request by SimonFinney**
Contributes to #2726

- Action to scaffold a convenience branch and draft PR for `carbon-v11` from PRs merged into `main` 
- Indicates to Kodiak to merge with a merge commit to avoid [re-resolving previously resolved conflicts](https://git-scm.com/docs/gitfaq#Documentation/gitfaq.txt-Whatkindsofproblemscanoccurwhenmerginglong-livedbrancheswithsquashmerges)

**Example:** https://github.com/SimonFinney/ibm-cloud-cognitive/pull/17 / https://github.com/SimonFinney/ibm-cloud-cognitive/pull/18

### CODE REVIEW

**Review by lee-chase — APPROVED** [review]
A good idea. Will be worth reviewing carefully the first few PRs created.

**Comment by elycheea** [comment]
@lee-chase @SimonFinney Should merge this first to test it out with the empty state PR #2766, yes?

**Comment by SimonFinney** [comment]
🤔 Issue with [recognising token](https://github.com/carbon-design-system/ibm-cloud-cognitive/actions/runs/4501987564/jobs/7923172558) — I'll need secrets access to debug.

**Comment by elycheea** [comment]
@SimonFinney Let me chase down Scott again.

**Pull request merged**
