### PR TITLE
Initial drop of IdeEmptyState

### PR DESCRIPTION
**Pull request by vladbalanescu**
Contributes to #

Another component transfer from the old unified design repo, IdeEmptyState

#### Changelog

Use the following command to list changes or manually list out new, changed and
removed files.

```
git diff --name-status $(git merge-base head master)
A       packages/cdai/src/components/IdeEmptyState/IdeEmptyState.js
A       packages/cdai/src/components/IdeEmptyState/IdeEmptyState.spec.js
A       packages/cdai/src/components/IdeEmptyState/IdeEmptyState.stories.js
A       packages/cdai/src/components/IdeEmptyState/README.md
A       packages/cdai/src/components/IdeEmptyState/_IdeEmptyState.scss
A       packages/cdai/src/components/IdeEmptyState/__snapshots__/IdeEmptyState.spec.js.snap
A       packages/cdai/src/components/IdeEmptyState/assets/api-error.lg.svg
A       packages/cdai/src/components/IdeEmptyState/assets/api-error.sm.svg
A       packages/cdai/src/components/IdeEmptyState/assets/default.lg.svg
A       packages/cdai/src/components/IdeEmptyState/assets/default.sm.svg
A       packages/cdai/src/components/IdeEmptyState/assets/deploy.lg.svg
A       packages/cdai/src/components/IdeEmptyState/assets/deploy.sm.svg
A       packages/cdai/src/components/IdeEmptyState/assets/index.js
A       packages/cdai/src/components/IdeEmptyState/assets/no-search-results.lg.svg
A       packages/cdai/src/components/IdeEmptyState/assets/no-search-results.sm.svg
A       packages/cdai/src/components/IdeEmptyState/assets/not-authorized.lg.svg
A       packages/cdai/src/components/IdeEmptyState/assets/not-authorized.sm.svg
A       packages/cdai/src/components/IdeEmptyState/index.js
A       packages/cdai/src/components/IdeEmptyState/test_assets/custom.lg.svg
A       packages/cdai/src/components/IdeEmptyState/test_assets/custom.sm.svg
M       packages/cdai/src/index.js
```

**New**

New ESLINT rule introduced as part of this PR, since `react/display-name` is to aggresive with implied defined components:
https://github.com/yannickcr/eslint-plugin-react/issues/597. If we are to keep this rule set to even warning, here's what we'd possibly getting:
image (2)

**Changed**

- N/A

**Removed**

- N/A

#### Testing / Reviewing

N/A

### CODE REVIEW

**Comment by CptPilot** [comment]
I believe we already have an empty state that follows the new pattern:

https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/159

**Comment by vladbalanescu** [comment]
@CptPilot Indeed, but that's under experimental not our prod ready component, so I won't feel confident to consume experiemental code in CP4I production code - FYI @asfordmatt

**Comment by asfordmatt** [comment]
Yes indeed, we need our "V1" components in here as-is, so consuming teams can easily transition to using this repo. The new "V2" components are still in development and not yet ready for production use.

**Review by asfordmatt — APPROVED** [review]
LGTM

**Pull request merged**
