### PR TITLE
feat(Datagrid): Extracts Filtering logic into useFilters hook (v11)

### PR DESCRIPTION
**Pull request by AlexanderMelox**
This PR takes the combined logic from filter flyout and panel and merges them into a hook so that the code stays DRY.

### CODE REVIEW

**Comment by AlexanderMelox** [comment]
Found an issue with checkbox, need to look into it

**Review by davidmenendez — APPROVED** [review]

**Comment by Ratheeshrajan** [comment]
I am not sure this is an issue, some times I need to click twice on the button to open the filter panel/flyout.

https://user-images.githubusercontent.com/305492/223712236-86ce75b3-1f97-48e8-9383-11d786b06b86.mov

**Comment by AlexanderMelox** [comment]
@Ratheeshrajan This is because our `DatagridToolbar` re renders multiple times in run time and causes the state to not go through sometimes. @elycheea This was one area I felt like we needed to refactor.

**Comment by elycheea** [comment]
@AlexanderMelox @Ratheeshrajan Let’s open an issue for this — I think the re-rendering issues are going to be noticeable to consumers/users so worth addressing.

**Comment by Ratheeshrajan** [comment]
@elycheea @AlexanderMelox opened a new issue for the above #2725. Otherwise, all the changes look good to me.

**Review by Ratheeshrajan — APPROVED** [review]

**Pull request merged**
