### PR TITLE
chore: a bunch of package upgrades

### PR DESCRIPTION
**Pull request by lee-chase**
A general package (not CDAI, Automation or Security) of minor versions. 

Jest bumped a major version to match other Jest packages. Tests still run successfully.

#### Changelog

M       package.json
M       packages/babel-preset-ibm-cloud-cognitive/package.json
M       packages/cli/package.json
M       packages/core/package.json
M       packages/experimental/package.json
M       packages/jest-config/package.json
M       packages/rollup-config/package.json
M       yarn.lock

### CODE REVIEW

**Comment by SimonFinney** [comment]
Thanks @lee-chase ! My only thought here is how do you propose we remain mindful of open source clearance (https://pedigree-service.wdc1a.cirrus.ibm.com/) on production dependencies in any of the packages we update via this method?

For this PR, I can only foresee `packages/experimental` as being a potential issue, as `@babel/runtime` (I think) is the only change that would make its way into production.

**Comment by lee-chase** [comment]
> Thanks @lee-chase ! My only thought here is how do you propose we remain mindful of open source clearance (https://pedigree-service.wdc1a.cirrus.ibm.com/) on production dependencies in any of the packages we update via this method?
> 
> For this PR, I can only foresee `packages/experimental` as being a potential issue, as `@babel/runtime` (I think) is the only change that would make its way into production.

Hadn't considered it @SimonFinney it would be a bizarre thing if we could not update minor versions as and when needed.

Can we raise this as a question. We also have added open source packages to experimental.

**Review by davidmenendez — APPROVED** [review]
I didn't run into any build or test errors. I also didn't see any errors in storybook. LGTM.

**Comment by SimonFinney** [comment]
Yeah, AFAIK patch version bumps are exempt from an additional review but minor aren't - I'd love to bring it up as a discussion point during the technical sync for a wider perspective as it's regularly communicated as a requirement on our side, but in my experience, I haven't come across a situation in which there had been an issue! 🤞 With that, I normally opt not to touch production dependencies aside from Carbon until there's a good reason to do it, just in case 😅

**Review by SimonFinney — APPROVED** [review]
LGTM! I'll update the issue templates tomorrow outlining what we discussed about new dependencies during today's sync

**Pull request merged**
