### PR TITLE
test(sass): add individual import tests

### PR DESCRIPTION
**Pull request by SimonFinney**
#### Affected issue

Contributes to #1132 

#### Proposed change

Add individual Sass import check to `cloud-cognitive` package — this currently uses `@carbon/bundler` but ideally it will leverage the [`@carbon/cli` package](https://github.com/carbon-design-system/carbon/blob/main/packages/themes/package.json#L27) before merging.

### CODE REVIEW

**Comment by SimonFinney** [comment]
@joshblack We were hoping to use `@carbon/cli` in favor of `@carbon/bundler` here, but it produces the following error —

```sh
$ /path/to/ibm-cloud-cognitive/node_modules/.bin/carbon-cli --help
Error: Cannot find module '../../../package.json'
Require stack:
- /path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/workspace.js
- /path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/commands/changelog.js
- /path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/node_modules/yargs/index.cjs
- /path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/cli.js
- /path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/bin/carbon-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/workspace.js:14:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/workspace.js',
    '/path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/commands/changelog.js',
    '/path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/node_modules/yargs/index.cjs',
    '/path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/src/cli.js',
    '/path/to/ibm-cloud-cognitive/node_modules/@carbon/cli/bin/carbon-cli.js'
  ]
}
```

I suspect because `@carbon/cli` was never intended to be used outside of the [Carbon monorepo](https://github.com/carbon-design-system/carbon) — what are your thoughts? We can defer to using `@carbon/bundler` if `@carbon/cli` is intended for internal use.

**Review by dcwarwick — DISMISSED** [review]

**Comment by dcwarwick** [comment]
@SimonFinney We can use the bundler for now, and I've opened #1144 to track replacing that with something else, whether carbon cli or something we do directly (I replaced the use of @carbon/bundler for the building with direct use of dart sass).

**Comment by joshblack** [comment]
@SimonFinney happy to clean up `@carbon/cli`! I think the fix should be simple enough to resolve the workspace root (we have some code for this in the project already)

A couple of questions:

- Are there any other commands that you are looking to use from `@carbon/cli`?
- Are you expecting the package to follow semver?

**Comment by SimonFinney** [comment]
> @SimonFinney happy to clean up `@carbon/cli`! I think the fix should be simple enough to resolve the workspace root (we have some code for this in the project already)
> 
> A couple of questions:
> 
> * Are there any other commands that you are looking to use from `@carbon/cli`?
> * Are you expecting the package to follow semver?

Amazing — thank you! I believe that's it for now, `sync` might also be nice but I don't believe it's really used for this repo so it's likely not worth the effort. For your second question, I can't see any immediate red flags if the package doesn't follow SemVer, but I may not be considering something obvious.

**Comment by joshblack** [comment]
@SimonFinney perfect. I'll add it to our sprint candidates for the next sprint (starting on August 23rd) that we're tracking over in: https://github.com/carbon-design-system/carbon/issues/9492

**Review by dcwarwick — APPROVED** [review]

**Pull request merged**
