### PR TITLE
fix(create full page): modal close issue fixed

### PR DESCRIPTION
**Pull request by jagathgj**
Contributes to #2438 

Modal not opening after closing it with outside click

#### What did you change?

Added onClose function with a state change(onClose={()=>setModalIsOpen(false)})

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by elycheea — COMMENTED** [review]
Looks good, but looks like we have code formatting issues.

I’m pretty sure you just need to add spaces around the arrow in `onClose` to address it.

**Comment by jagathgj** [comment]
@elycheea Thanks for reviewing. Kindly look at updated code.

**Review by elycheea — APPROVED** [review]
Looks good! Can we also open a PR for this to the `carbon-v11` branch? Thank you!

**Comment by elycheea** [comment]
@allcontributors add @jagathgj for code

**Pull request merged**
