### PR TITLE
docs(tearsheet): update "portalTarget" prop name in stories

### PR DESCRIPTION
**Pull request by janhassel**
While working with `Tearsheet` I've found myself digging through the source code to find out how to render it in a different node rather than `document.body` because `portalTargetCustomDomNode` didn't work despite being listed in the storybook controls.
I found out that the prop is actually called `portalTarget`.

This PR updates the storybook control to reflect this.

@lee-chase Please let me know if this was intentional / I'm overseeing something.

#### What did you change?
- Update `portalTargetCustomDomNode` to `portalTarget` in the storybook controls for `TearsheetSheel`, `Tearsheet` and `TearsheetNarrow` stories.

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by davidmenendez — DISMISSED** [review]

**Review by lee-chase — CHANGES_REQUESTED** [review]
This was set to something other than portalTarget to avoid implying that the property is a boolean. 

A better solution would be to change the storybook property to portalTarget and the control type to "control: { type: 'radio' }" or "control: { type: 'select' }" and map the desired value to the property. As it's only two states the radio is probably the best option.

**Comment by janhassel** [comment]
@lee-chase So if I understand correctly, you'd like to see the control as a radio group with two options (e.g. `document.body (default)` and `ref.current`)?

**Comment by lee-chase** [comment]
> 

That's right @janhassel, perhaps check the description is clear to you too.

**Comment by janhassel** [comment]
@lee-chase Upon thinking more about this: should there even be a control for this prop or should it just be disabled in the storybook as there's nothing that really changes visibly to the user playing around with the knobs. This could avoid confusion over what you can pass into `props.portalTarget`

**Comment by lee-chase** [comment]
@janhassel Storybook is both a demonstration and documentation. As a result, we should list all properties.

**Comment by janhassel** [comment]
@lee-chase I'm not talking about removing the prop from the list but just disabling the control as it doesn't produce any visually different output and doesn't really have an appropriate control. So doing the same as you currently do with `props.influencer`, `props.onClose`, `props.navigation` and so on...

**Comment by janhassel** [comment]
@lee-chase I just pushed an update outlining what I mean. Let me know what you think!

**Comment by lee-chase** [comment]
@janhassel a fair point and an acceptable solution. In order for the `portalTarget` to appear on the docs page with a suitable description it appears to be necessary to duplicate the `TearsheetShell.propTypes` entry in Tearsheet and TearsheetNarrow, as per influencer.

**Comment by janhassel** [comment]
@lee-chase Pushed an update. The `portalTarget` prop now appears in the storybook docs argstable.

**Review by lee-chase — APPROVED** [review]
Happy with the changes

**Comment by janhassel** [comment]
@davidmenendez Looks like GitHub marked your review as stale over the time. Would you mind checking over it again?

**Pull request merged**
