### PR TITLE
feat: feature flagging in v1 with example

### PR DESCRIPTION
**Pull request by lee-chase**
Contributes to #2747

The same faetures as PR 2748 but without the DataGrid feature flag bit, just update the example component.

#### What did you change?

Merged feature flag examples down from V2.

#### How did you test and verify your work?

Storybook

### CODE REVIEW

**Comment by davidmenendez** [comment]
still reviewing the code, but i'm seeing this in the preview
Screenshot 2023-04-25 at 2 05 24 PM

**Review by davidmenendez — COMMENTED** [review]
code looks good to me. i think the storybook toast just needs to be fixed

**Review by davidmenendez — CHANGES_REQUESTED** [review]
code looks good to me. i think the storybook toast just needs to be fixed

**Comment by lee-chase** [comment]
Good catch @davidmenendez an issue with the V10 notification in effect.

**Pull request merged**
