### PR TITLE
chore(Datagrid): scrollbar styling

### PR DESCRIPTION
**Pull request by Ratheeshrajan**
Contributes to #2174 

Covers the scrollbar styling and behavior in the data table

#### What did you change?
- Nawwow scrollbar styling for WebKit browser 
- Datagrid horizontal scrollbar appears on hover.

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by elycheea — CHANGES_REQUESTED** [review]
While I do think this is a clever approach to getting the scrollbar to appear on hover only, since this is also OS specific behavior, it may be better for us to clarify with the designers who wrote the guidance on this. It’s probably better to keep with the OS settings rather than creating custom behavior so that this remains in the user’s control. Also, when the overflow style changes, we also can see a shift in the DOM as the scrollbar appears. This is more noticeable on the pagination story. 

That said, we should still investigate whether or not we need custom scrollbar styling as opposed to the browser default here too. In the [Ten Thousand Entries](https://deploy-preview-2193--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--ten-thousand-entries) story, we do add a custom “virtual scrollbar” so perhaps our custom scrollbar is to keep vertical/horizontal styles consistent?

**Comment by elycheea** [comment]
@Ratheeshrajan See comments from earlier when you get the chance, but can you also resolve the conflict in datagrid.scss?

**Comment by Ratheeshrajan** [comment]
@elycheea The changes in the current PR have been removed and merged in [2171](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2171/files). Are we still required to keep the changes?

**Comment by elycheea** [comment]
Good point. Let’s close this for now. Since the changes themselves were fairly small, we can make them again if still necessary.

**Pull request closed without merging**
