### PR TITLE
docs(CODEOWNERS): update CODEOWNERS for review assignment

### LINKED ISSUE #13: Define CODEOWNERS and teams
## Summary

Identify and define CODEOWNERS and teams for design and development to automatically assign for PRs.

### PR DESCRIPTION
**Pull request by SimonFinney**
Closes #13 

#### Changelog

**Changed**

Update `CODEOWNERS` review assignment to a catch-all for developers to all files, and specific folks to currently active individual packages

### CODE REVIEW

**Comment by SimonFinney** [comment]
@carbon-design-system/ibm-cloud-paks This is a best-guess PR and doesn't fully reflect ownership across the entire repo - @davidmenendez , @lee-chase , and @moores2 is there somewhere specific that makes sense to include y'all here?

**Comment by lee-chase** [comment]
> @carbon-design-system/ibm-cloud-paks This is a best-guess PR and doesn't fully reflect ownership across the entire repo - @davidmenendez , @lee-chase, and @moores2 is there somewhere specific that makes sense to include y'all here?

Depends on the purpose of code owner assignment in the repo. If it is purely to limit how CDAI, Security and future core library are created then we probably do not need any special permissions. If it is to enable a lighter touch then add us to experimental and core.

**Comment by SimonFinney** [comment]
Cool - For now, I see owners for individual packages as being sufficient, and envision `core` and `experimental` as being owned by everyone.

Later down the line, we could consider having owners on individual patterns, for example, we could tag Cameron for any incoming changes to the `PageHeader`.

**Comment by SimonFinney** [comment]
Converting to draft for now until the repo grows some more

**Pull request closed without merging**
