### PR TITLE
fix: header row horizontal scroll and scrollbar style

### PR DESCRIPTION
**Pull request by kai-liu**
When doing horizontal scrolling in datagrid, header row would not scroll;

In certain datagrid stories(eg., Empty State, Infinite Scroll, Ten Thousand Entries) , the style of scroll bar is set to browser's default style instead of IBM's scrollbar style.

#### What did you change?
`datagrid.scss` 
Changed overflow and display configs so that header row can scroll properly when overflow occurs.
Added selectors to change the scrollbar style of stories to improve consistency

#### How did you test and verify your work?
verified visually in storybook.

### CODE REVIEW

**Review by markkulube — CHANGES_REQUESTED** [review]
@kai-liu 

It could help reviewers if before and after images are included.

Speaking of reviewers, please specify @holmansze (you are welcome to add me too - i can chime in thoughts if i've a some moments)

**Review by matthewgallo — APPROVED** [review]
Thanks for addressing this @kai-liu 🎉

**Comment by matthewgallo** [comment]
@markkulube, @kai and I have reviewed this work earlier in the week. I was able to confirm the changes fix the horizontal scrolling issue with the column headers. Typically speaking though, the before and after images are helpful, I agree!

**Comment by kai-liu** [comment]
Thanks @markkulube and @matthewgallo for the reminder. I will make sure future PRs are more illustrative of the issue. I will also include the necessary reviewers in future PRs.

**Comment by markkulube** [comment]
@matthewgallo thank you for the heads up.

@kai-liu great job!

**Pull request merged**
