### PR TITLE
Feature/create loading bar component

### PR DESCRIPTION
**Pull request by JessNah**
Implements and creates new component: LoadingBar,
For issue:
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/835

### CODE REVIEW

**Comment by lee-chase** [comment]
Hey, @JessNah I've pushed a couple of minor fixes, but otherwise looks like a pretty good first pass.

Can you take a look at the following:
1. Create an issue using the "New Component or Pattern" template adding as much information as you can. In order to progress we will definitely need to identify the design maintainer.
2. There are a few CI-Check/linting fails. Most of these are down to our use of Carbon CSS order and the requirement to use Carbon tokens for layout, typography, color and motion. See the guidelines section of the Carbon website https://www.carbondesignsystem.com/guidelines/2x-grid/overview/

P.S. If you are using VSCode with ESLint, Prettier and Stylelint extensions you should get some wiggly red lines to show you where the linter is complaining.

**Comment by andrea-gm** [comment]
Here is the design https://pages.github.ibm.com/cdai-design/pal/components/progressive-loading-bar

**Comment by JessNah** [comment]
@lee-chase , Hey Lee, thanks for taking the time to review my pull request and for your feedback. I just opened this new component issue here:
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/835,
I am not sure if the design maintainer is supposed to be me / Emmeline Hewstone (she created the design pattern entry for this component), or if that's meant to be someone internally from ibm-cloud-cognitive.. so I left that blank. Hope that's ok

**Comment by JessNah** [comment]
@lee-chase Hey Lee, sorry to trouble you. I am struggling a bit with the linting fails. I installed the vscode extensions - eslint/stylelint/prettier, though not seeing any red squiggles on the editor :/
Is there any script I should run?

**Comment by lee-chase** [comment]
You might need to have lint on save turned on in vscode. You can run the ci-check script manually from the command line.

**Review by lee-chase — APPROVED** [review]
LGTM

**Comment by JessNah** [comment]
Thank you @lee-chase , for helping get this merged in! I am sorry I did not get a chance to fix up the linting errors. I really appreciate you getting these resolved and taking the time to look at this PR. Thanks a lot.

**Pull request merged**
